# Generated by Django 3.1.7 on 2021-03-02 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PyTip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.CharField(blank=True, max_length=500, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('tweet_text', models.CharField(blank=True, max_length=500, null=True)),
                ('tweet_link', models.CharField(blank=True, max_length=500, null=True)),
                ('external_url', models.CharField(blank=True, max_length=5000, null=True)),
                ('posted_by', models.CharField(blank=True, max_length=200, null=True)),
                ('like', models.IntegerField(blank=True, null=True)),
                ('retweet', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
